server.port=8082
spring.application.name=invoice-service

# Customer Service URL
customer.service.url=http://localhost:8081

# Logging
logging.level.com.example.invoiceservice=DEBUG

# Thymeleaf
spring.thymeleaf.cache=false